#!/usr/bin/env bash
# Copy the current local site state (MAMP) into the repo:
#   - our own code (TRACKED_CODE)       → wp-content/...
#   - uploads (minus generated caches)  → wp-content/uploads
#   - the database                      → db/viktorin.sql (one row per line, diff-friendly)
#   - versions of core/plugins/themes   → versions.txt
# Runs automatically from the pre-commit hook. Safe to run any time.
source "$(dirname "${BASH_SOURCE[0]}")/config.sh"
check_db

# ── Code ─────────────────────────────────────────────────────────────────────
for path in "${TRACKED_CODE[@]}"; do
  src="$WP_DIR/wp-content/$path"
  dst="$REPO_DIR/wp-content/$path"
  [ -d "$src" ] || { echo "  (skip $path – not in MAMP)"; continue; }
  mkdir -p "$dst"
  rsync -a --delete --exclude '.DS_Store' --exclude 'node_modules/' "$src/" "$dst/"
done
info "Code synced: ${TRACKED_CODE[*]}"

# ── Uploads ──────────────────────────────────────────────────────────────────
excludes=()
for e in "${UPLOADS_EXCLUDES[@]}"; do excludes+=(--exclude "$e"); done
mkdir -p "$REPO_DIR/wp-content/uploads"
rsync -a --delete "${excludes[@]}" "$WP_DIR/wp-content/uploads/" "$REPO_DIR/wp-content/uploads/"
info "Uploads synced"

# ── Database ─────────────────────────────────────────────────────────────────
mkdir -p "$REPO_DIR/db"
tmp="$(mktemp -t viktorin-sql)"
dump_opts=(
  --defaults-extra-file="$MYCNF"
  --skip-extended-insert   # one INSERT per row → readable git diffs
  --skip-comments
  --skip-dump-date
  --order-by-primary
  --single-transaction
  --no-tablespaces
  --default-character-set=utf8mb4
)
opt_table="${TABLE_PREFIX}options"

# Everything except wp_options…
"$MYSQLDUMP" "${dump_opts[@]}" --ignore-table="$DB_NAME.$opt_table" "$DB_NAME" > "$tmp"
# …then wp_options without transients/cron (pure noise, WordPress rebuilds them).
"$MYSQLDUMP" "${dump_opts[@]}" \
  --where="option_name NOT LIKE '\\_transient\\_%' AND option_name NOT LIKE '\\_site\\_transient\\_%' AND option_name <> 'cron'" \
  "$DB_NAME" "$opt_table" >> "$tmp"

# Drop AUTO_INCREMENT counters from CREATE TABLE so they don't churn diffs.
sed -E 's/ AUTO_INCREMENT=[0-9]+//' "$tmp" > "$DB_FILE"
rm -f "$tmp"
info "Database dumped → db/$(basename "$DB_FILE") ($(du -h "$DB_FILE" | cut -f1 | tr -d ' '))"

# ── Versions ─────────────────────────────────────────────────────────────────
{
  echo "# Generated by scripts/snapshot.sh – versions of everything NOT in git."
  echo "wordpress $(perl -ne "print \$1 if /\\\$wp_version\s*=\s*'([^']+)'/" "$WP_DIR/wp-includes/version.php")"
  echo
  echo "[themes]"
  for d in "$WP_DIR"/wp-content/themes/*/; do
    [ -f "$d/style.css" ] || continue
    printf '%s %s\n' "$(basename "$d")" "$(perl -ne 'if (/^\s*\*?\s*Version:\s*(\S+)/i) { print $1; exit }' "$d/style.css")"
  done
  echo
  echo "[plugins]"
  for d in "$WP_DIR"/wp-content/plugins/*/; do
    main="$(grep -l 'Plugin Name:' "$d"*.php 2>/dev/null | head -1 || true)"
    [ -n "$main" ] || continue
    printf '%s %s\n' "$(basename "$d")" "$(perl -ne 'if (/^\s*\*?\s*Version:\s*(\S+)/i) { print $1; exit }' "$main")"
  done
  echo
  echo "[active_plugins]"
  mysql_q -N -e "SELECT option_value FROM ${opt_table} WHERE option_name='active_plugins'" \
    | perl -ne 'print "$1\n" while /s:\d+:"([^"]+)"/g'
  echo
  echo "[active_theme]"
  mysql_q -N -e "SELECT option_name, option_value FROM ${opt_table} WHERE option_name IN ('template','stylesheet') ORDER BY option_name DESC"
} > "$REPO_DIR/versions.txt"
info "versions.txt updated"
echo "✔ Snapshot done"
